### PR TITLE
Add persistence

### PR DESCRIPTION
**Pull request by nakajima**
I think I've got all the existing functionality backed by the DB now. The DB should be encrypted with SQLCipher though right now the passphrase is always the same. There's some other cleanups that would be good to do but this PR is already pretty huge so I feel like it'd be good land what we've got so far.

### CODE REVIEW

**Comment by nakajima** [comment]
BTW, happy to go over all these changes on a call if that'd be easier.

**Review by elisealix22 — COMMENTED** [review]
OK this is unreal, Pat! Can't believe you got it working so quickly 🤩. The one thing I noticed in testing is the sql transactions seem to take a while (~20s) on my account with hundreds of convos. I can see the debug console printing like mad and it seems to take significantly longer to show the initial list of convos or to pull to refresh, but perhaps is something we can optimize in the future?

Also, if I close the app and cold start, it seems to show the fullscreen loading spinner instead of the previously cached items. Idk if that's meant to be supported in this PR!

Happy to re-review asap if you want to merge as-is and work on perf as a follow-up, but I included a screen recording so you can see what I'm talking about.

<details>
<summary>Cold start and pull to refresh demo</summary>

https://user-images.githubusercontent.com/556051/216684888-034a279c-0399-4f24-99cb-a0f004c9f069.MP4

</details>

**Comment by nakajima** [comment]
I'm _guessing_ the long time is due to the loading of all the most recent messages, but maybe it'd be good to check out what's getting printed to the console? I can take a look at this before merging here.

**Comment by nakajima** [comment]
Ok, things are much faster now. Doing an ENS lookup for every conversation was a fun lil N+1. I also fixed the loading indicator always appearing.

**Review by nplasterer — APPROVED** [review]
This looks good to me! I wasn't able to get it running locally but I think it might be a me/new XCode issue.

**Review by elisealix22 — APPROVED** [review]
Confirmed so much faster! ⚡

**Pull request merged**
